export type PredictedApartment = {
  index: number;
  city: number;
  floor: number;
  total_area: number;
  living_area: number;
  kitchen_area: number;
  room_count: number;
  height: number;
  is_studio: number;
  view_building: number;
  view_city: number;
  view_cottages: number;
  view_field: number;
  view_forest: number;
  view_north: number;
  view_parking: number;
  view_playground: number;
  view_school: number;
  view_street: number;
  view_water: number;
  view_west: number;
  view_yard: number;
  total_price: number;
  total_price_pred: number;
  difference_val: number;
  difference_percent: number;
};
